name: TextifyApp
options:
  bundleIdPrefix: com.textify
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  TextifyApp:
    type: application
    platform: iOS
    sources:
      - path: TextifyApp/Sources
        excludes:
          - "**/.DS_Store"
    resources:
      - path: TextifyApp/Resources
    settings:
      base:
        INFOPLIST_FILE: TextifyApp/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.textify.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        SWIFT_STRICT_CONCURRENCY: complete
    dependencies:
      - package: TextifyKit

packages:
  TextifyKit:
    path: ../TextifyKit
